config/routes.rb
Rails.application.routes.draw do
  
  resources :reports do
    
    collection do
      post  :generate_report
    end
    
  end
  
  get '/run' => "reports#run", :as => "run_report"

  root 'reports#run'

  
  
end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  #before_action :set_report, only: [:show, :edit, :update, :destroy]
  
  # for working with RESTul services
  require 'rest_client'
  
  # for base64 encoding
  require 'base64'
  
  # for escaping chars in URL
  require 'uri'
  
  
  
  #define constants
  COUNTY_CODE = :COUNTY_CDE
  STATUS_CODE = :statusCdes
  SPONSOR_CODE = :sponsorCdes
  


  # GET /reports
  # GET /reports.json
  def index
    # @reports = Report.all
    
    redirect_to '/'
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    redirect_to '/'
  end

  # GET /reports/new
  def new
    
    redirect_to '/'
    
    #@report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    
    redirect_to '/'
    
=begin   
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
    
=end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    
    redirect_to '/'
    
=begin
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
    
=end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    
    
    redirect_to '/'
    
=begin
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
    
=end
  end
  
  
  def run   
     @report = Report.new
  end
  
  def generate_report
    
    #init variables
    @county = nil
    county_str = ""
    
    @sponsor = nil
    sponsor_str = ""
    
    @status = nil
    status_str = ""
    
    
    
    # retrieve the parameters from input field
    retrieve_params(params)
    
    
    #if there is no repeort name to run, just return
    if @path_to_report.empty?
      render :text => "No report name specified, nothing to run".html_safe
      return
    end
    
    #print some for debugging output
    #Rails.logger.info "Report_id is #{@report_id}"
    #Rails.logger.info "server_name is #{@server_name}"
    
  
    # encode the report's user name and password in HTTP header for basic authentication
    user_auth_str = "#{@login}|#{@organization_id}"        
    auth = "Basic " + Base64::strict_encode64("#{user_auth_str}:#{@password}") 
    
    
    #build the county param query string
    if @county != nil
      
      county_str = build_query_string(@county, COUNTY_CODE)
      
      Rails.logger.debug "*************County_str is #{county_str}"
      
    end
        
    
    if @sponsor != nil
      
      sponsor_str = build_query_string(@sponsor, SPONSOR_CODE)
      
      Rails.logger.debug "*************Sponsor_str is #{sponsor_str}"
      
    end
    
    
    if @status != nil
      
      status_str = build_query_string(@status, STATUS_CODE)
      
      Rails.logger.debug "*************Status_str is #{status_str}"
      
    end
    
    
=begin    
    #determine the output format for the report
    output_format = ""
    
    if @report_format == "pdf"
      #generate output in html format, then use pdfkit converts the output back to pdf. This is because pdfkit's limitation.
      #output_format = 'html'
      output_format = @report_format
    else
      output_format = @report_format
    end
=end
   
    # build the report URL
    report_url =  "http://#{@server_name}/jasperserver-pro/rest_v2/reports#{@path_to_report}.#{@report_format}"
    
    #append the starting character to the URL if there is any query parameters
    if (!county_str.empty? || !sponsor_str.empty? || !status_str.empty?)
      report_url += '?'
    end
    
    #append the county str to the report URL
    if !county_str.empty?
      report_url += county_str
    end
    
    if !sponsor_str.empty?
      report_url += sponsor_str
    end
    
    if !status_str.empty?
      report_url += status_str
    end
    
    #remove the last extra character
    if (!county_str.empty? || !sponsor_str.empty? || !status_str.empty?)
      report_url.chop!
    end
    
    #sanitize the report URL - to replace the space with %20, for example
    report_url = URI.escape(report_url)
    
    Rails.logger.info "Report path is: #{report_url}"
    
    begin
      #run the report
      response = RestClient.get("#{report_url}", :authorization=>auth)
      #response = RestClient.post("#{report_url}", :authorization=>auth)
    rescue Exception => exception
      
      Rails.logger.info "Got exception when report was running: #{exception.message}"
      render plain: "Error! Got exception when report was running: #{exception.message}"
      return
    end
    
    case @report_format
    when "pdf"
      Rails.logger.debug "render pdf" 
      send_data response, :filename => "#{@report_output_file_name}.#{@report_format}", :type => "application/pdf"
    
      #send_file(pdf, :filename => "#{@report_output_file_name}.#{@report_format}", :disposition => 'inline', :type => "application/pdf")
     ##       :disposition  => "inline" # either "inline" or "attachment"
      return
    when "xml"
      Rails.logger.debug "render xml"
      render xml: response
      return
    when "html"
      Rails.logger.debug "render html"
      render :text => response.html_safe
      return
    else
      Rails.logger.debug "Don't know what to render. Use html format"
      render :text => response.html_safe
      return
    end
    
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:report_name, :server_name, :server_port, :login, :password, :organization_id, :report_format, :report_output_file_name, :path_to_report, :report_id)
    end
    
    # retrieve the parameters from input field
    def retrieve_params(params)
      
      
=begin
       = params[:report][]
       = params[:report][]
        = params[:report][]
        = params[:report][]
        
        
=end
      
      @report_id = params[:report][:report_id]
      @server_name = params[:report][:server_name]
      @server_port = params[:report][:server_port]
      @login = params[:report][:login]
      @password = params[:report][:password]
      @organization_id = params[:report][:organization_id]
      @report_format = params[:report_format]
      @report_output_file_name = params[:report][:report_output_file_name]
      @path_to_report = params[:report][:path_to_report]
      
      
      if params[COUNTY_CODE] != nil
        @county = params[COUNTY_CODE]
      end
      
      if params[SPONSOR_CODE] != nil
        @sponsor = params[SPONSOR_CODE]
      end
      
      if params[STATUS_CODE] != nil
        @status = params[STATUS_CODE]
      end
      
      if @path_to_report.empty? && params[:report_path_selection] != nil
        @path_to_report = params[:report_path_selection]
        
        Rails.logger.debug "*********** Get report path value from selection box: #{@path_to_report}"
      end
      
      
      
    end
    
    
    
    def build_query_string(query_param, code)
      
      qry_str = ""
      
      query_param.each do |ct|
        qry_str += "#{code}=#{ct}&" 
      end
      
      #remove the last extra char
      #qry_str.chop!
      
      return qry_str
      
    end
    
    
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JasperRailsRestApi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :report_name %><br>
    <%= f.text_field :report_name %>
  </div>
  <div class="field">
    <%= f.label :server_name %><br>
    <%= f.text_field :server_name %>
  </div>
  <div class="field">
    <%= f.label :server_port %><br>
    <%= f.number_field :server_port %>
  </div>
  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :organization_id %><br>
    <%= f.text_field :organization_id %>
  </div>
  <div class="field">
    <%= f.label :report_format %><br>
    <%= f.text_field :report_format %>
  </div>
  <div class="field">
    <%= f.label :report_output_file_name %><br>
    <%= f.text_field :report_output_file_name %>
  </div>
  <div class="field">
    <%= f.label :path_to_report %><br>
    <%= f.text_field :path_to_report %>
  </div>
  <div class="field">
    <%= f.label :report_id %><br>
    <%= f.text_field :report_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/_run_report_form.html.erb
<%= form_for(@report, :url => {:controller => "reports", :action => "generate_report"}) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being run:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= field_set_tag 'Server Information', :class => 'deco1' do %>
 
  <div class="field">
    <%= f.label :server_name %><br>
    <%= f.text_field :server_name, :value => 'reporttest.mtc.ca.gov' %>
  </div>
  
  <div class="field">
    <%= f.label :server_port %><br>
    <%= f.number_field :server_port, :value => '80' %>
  </div>
  
<% end %>
  
  
<%= field_set_tag 'User Information', :class => 'deco1' do %>
  
  <div class="field">
    <%= f.label 'User Name/ID' %><br>
    <%= f.text_field :login, :value => 'fmsread' %>
  </div>
  
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password, :value => 'fmsread' %>
  </div>
  
  <div class="field">
    <%= f.label :organization_id %><br>
    <%= f.text_field :organization_id, :value => 'mtc_pa' %>
  </div>
  
  
<% end %>
  
  
<%= field_set_tag 'Report Information', :class => 'deco1' do %>
  
  <div class="field">
  	<!-- %= f.label "Select a report to be run" %><br -->
    <%= select_tag(:report_path_selection, options_for_select([['Select a report to be run',''],
    												['/fms/production/reports/internal/Agency_Funding_Report', '/fms/production/reports/internal/Agency_Funding_Report'], 
    												['/fms/production/reports/internal/Project_Conformity_Summary_Report', '/fms/production/reports/internal/Project_Conformity_Summary_Report'], 
    												['/fms/production/reports/public/single_point_of_contact_report', '/fms/production/reports/public/single_point_of_contact_report']
    												
    												]), {class: "select_box_medium"})%>
  	
    
  </div>
  <!-- ['/fms/production/reports/internal/project_comprehensive_funding_authority', '/fms/production/reports/internal/project_comprehensive_funding_authority'] -->
  
  <div class="field">
    <%= f.label "Or type in a path for the report" %><br>
    <p class="hint">Note: Entry in this input field will take precedence(ie. /fms/production/reports/public/ARRA_FHWA)</p>
    <%= f.text_field :path_to_report, :value => '', :size => 120 %>
  </div>
  
  <!-- multiple value selection  -->
  <div class="field">
    <%= f.label "County parameter:" %><br>
    <%= select_tag(:COUNTY_CDE, options_for_select([['Alameda', 'ALA'], ['Contra Costa', 'CC'], ['Marin', 'MRN'], ['Napa', 'NAP'], ['Regional', 'REG'], ['San Francisco', 'SF']]), {class: "select_box", multiple: true})%>
  </div>
  
  <!-- multiple value selection  -->
  <div class="field">
    <%= f.label "Sponsor parameter:" %><br>
    <%= select_tag(:sponsorCdes, options_for_select([['AMTRAK', 'AMTRAK'], ['Alameda (City)', 'Alameda'], ['Alameda Contra Costa Transit District (AC Transit)', 'AC Transit'], 
    												['Alameda County', 'Alameda County'], ['Calif. High Speed Rail Authority', 'CA HS Rail'], 
    												['Albany', 'Albany']]), {class: "select_box", multiple: true})%>
  </div>
  
  <!-- multiple value selection  -->
  <div class="field">
    <%= f.label "Status parameter:" %><br>
    <%= select_tag(:statusCdes, options_for_select([['Active', 'ACTIVE'], ['Proposed', 'PROPOSED']]), {class: "select_box", multiple: true})%>
  </div>
  
  
<% end %>

  
<%= field_set_tag 'Report Output Information', :class => 'deco1' do %>
  
<!--
  <div class="field">
    <%= f.label 'Report Format (html or xml)' %><br>
    <%= f.text_field :report_format, :value => 'html' %>
  </div>
 --> 
  <div class="field">
  	<%= f.label 'Report Format' %><br>
    <%= select_tag(:report_format, options_for_select([
    												['html', 'html'], 
    												['pdf', 'pdf'], 
    												['xml', 'xml']					
    												]), {class: "select_box"})%>
  	
    
  </div>
 
  <div class="field">
    <%= f.label 'File Name for the Generated Report' %><br>
    <%= f.text_field :report_output_file_name, :value => 'my_report' %>
  </div>
  
  
<% end %>
  
   
  
<!--  
  <div class="field">
    <%= f.label 'Report ID/Name to be run' %><br>
    <%= f.text_field :report_id %>
  </div>
  
 
  <div class="field">
    <%= f.label :report_name %><br>
    <%= f.text_field :report_name %>
  </div>
 --> 
  
  <div class="actions">
    <%= f.submit  'Run Report' %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<h1>Listing reports</h1>

<table>
  <thead>
    <tr>
      <th>Report name</th>
      <th>Server name</th>
      <th>Server port</th>
      <th>Login</th>
      <th>Password</th>
      <th>Organization</th>
      <th>Report format</th>
      <th>Report output file name</th>
      <th>Path to report</th>
      <th>Report</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.report_name %></td>
        <td><%= report.server_name %></td>
        <td><%= report.server_port %></td>
        <td><%= report.login %></td>
        <td><%= report.password %></td>
        <td><%= report.organization_id %></td>
        <td><%= report.report_format %></td>
        <td><%= report.report_output_file_name %></td>
        <td><%= report.path_to_report %></td>
        <td><%= report.report_id %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/run.html.erb
<p class="title">JasperReport - Report Tester</p>

<%= render 'run_report_form' %>

<!--
<%= link_to 'Back', reports_path %>
>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Report name:</strong>
  <%= @report.report_name %>
</p>

<p>
  <strong>Server name:</strong>
  <%= @report.server_name %>
</p>

<p>
  <strong>Server port:</strong>
  <%= @report.server_port %>
</p>

<p>
  <strong>Login:</strong>
  <%= @report.login %>
</p>

<p>
  <strong>Password:</strong>
  <%= @report.password %>
</p>

<p>
  <strong>Organization:</strong>
  <%= @report.organization_id %>
</p>

<p>
  <strong>Report format:</strong>
  <%= @report.report_format %>
</p>

<p>
  <strong>Report output file name:</strong>
  <%= @report.report_output_file_name %>
</p>

<p>
  <strong>Path to report:</strong>
  <%= @report.path_to_report %>
</p>

<p>
  <strong>Report:</strong>
  <%= @report.report_id %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>